export { default as HomerBackground } from "./homer-background.jpg";
export { default as SkyBackground } from "./sky-background.jpg";
export { default as CloseButton } from "./close.png";
export { default as AssinarImage } from "./suscribe-img.jpg";
export { default as BartImage } from "./bart.png";
export { default as HomerImage } from "./homer.png";
export { default as LisaImage } from "./lisa.png";
export { default as MaggieImage } from "./maggie.png";
export { default as MargeImage } from "./marge.png";
